### ISSUE TITLE
January 2022 Contribution

### ISSUE THREAD

**Issue by pnpdude** [ArthSwap/ArthSwap-Community-Program-ACP-#1]
Telegram Username: @pnp_404

Discord Username: @PnP#3971

ASTR Wallet Address: 0x61709f32808EBCD44b0D7c9271a4A16D167A7AC4

Contributions:

CM - Manage and support Thai telegram/Discord and Main English Discord community chat.
*There is no stat for Telegram atm, we just onboard users.
![image](https://user-images.githubusercontent.com/90048622/151705255-b7477a85-374f-44dd-a0f6-5d259b23d24c.png)

Translate short news into Thai and Rephrase from Official Articles as follow:

https://medium.com/arthswap-thai-community/%E0%B8%A3%E0%B8%B9%E0%B9%89%E0%B8%88%E0%B8%B1%E0%B8%81-arthswap-dapp-%E0%B9%81%E0%B8%A3%E0%B8%81%E0%B8%9A%E0%B8%99-astar-network-8b088bc71f50

https://medium.com/arthswap-thai-community/%E0%B9%80%E0%B8%A3%E0%B8%B4%E0%B9%88%E0%B8%A1%E0%B9%83%E0%B8%8A%E0%B9%89%E0%B8%87%E0%B8%B2%E0%B8%99-arthswap-c29ddb681498

![image](https://user-images.githubusercontent.com/90048622/151705307-34cb2654-e3e7-4266-a09c-170037d5dc8c.png)

VSM - tweet 1 tweet
Summarize of ArthSwap,
https://twitter.com/xpnp404/status/1486379117436354560?s=20&t=TvKqZ5BpTK6vnpBLLzPJNg
![image](https://user-images.githubusercontent.com/90048622/151705376-e26c8075-da58-4e15-bfff-d8f5414e0d8e.png)

**edited*
For Supplementary Tasks,
TT- Create Wallet tutorial from Scratch on Both Medium and Subsocial
https://panupongpnp.medium.com/arthswap-wallet-101-af8990ecaf95
https://app.subsocial.network/6215/arth-swap-wallet-101-31173

If you have any question, feels free to ask
Thank you,

**Comment by ArthSwap** [comment]
Thank you for your support.
CM-50/50
VSM-50/50
TT-10/10
We really appreciate your support every day.
